** TODO Programas en C++ y Python [66%]
   DEADLINE: <2016-11-21 lun>
   + [X] Programa en C++, no olvidar al correr guardar los resultados [100%].
     1. [X] Implementar la estructura célula [100%]
	1. [X] Atributos [100%]:
	   - [X] Crear Atributo entero que indique la dirección del movimiento (1=arriba, 2=derecha, etc.)
	   - [X] Crear Atributo X e Y que indiquen la posición actual.
	   - [X] Atributo entero que diga si la célula está infectada, susceptible o removido. (S=1, I=2, R=3).
	2. [X] Métodos [100%]
	   * [X] Hacer que se mueva la célula a cualquier lado (la probabilidad de moverse a un lado 
	    determinado es la misma para todos los lados.
	   * [X] Si la célula se encuentra infectada, determinar en una iteración dada con la probabilidad dada
	     si pasa a ser removido o no.
	   * [X] Hacer que la célula rote; puede rotar a cualquier lado con igual probabilidad.
	   * [X] Hay que evitar que la célula se salga de los límites del mapa.
   
     2. [X] Funciones Globales [100%]
	* [X] Función que determina cuántas celulas infectadas hay al lado de ella para calcular si se convertirá
	  en una célula infectada o no (en caso de que la susodicha sea susceptible).
	* [X] Función que mueve todas las células.
	* [X] Función que rota todas las células.
	* [X] Función que cure a todas las células infectadas con el método de la estructura célula
	* [X] Función que coloque a todas las células uniformemente en la malla bidimensional (arranque).
	* [X] Función que haga que M células se infecten aleatoriamente, con M el número de infectados inicial
      
     3. [X] Variables Globales [100%]
	* [X] Número N para hacer la malla bidimensional NxN.
	* [X] Población inicial susceptible.
	* [X] Población inicial enferma.
	* [X] Probabilidad de volverse inmune (después hay que adecuar esto para cambiarlo con for).
     
     4. [X] cout<< el tiempo transcurrido, número de susceptibles, de infectados y de removidos.
	   
      
   + [X] Programa en Python [100%].
     * [X] Recibir los datos provenientes del archivo de texto.
     * [X] Graficar.
     * [X] Tener pendiente que después toca graficar la población susceptible final contra la probabilidad
       de curarse.
   
   + [ ] Hacer el artículo.
